-- MySQL Script generated by MySQL Workbench
-- Mon Aug 18 22:24:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema UniversityDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `DEPARTMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DEPARTMENT` ;

CREATE TABLE IF NOT EXISTS `DEPARTMENT` (
  `Dept_Code` INT NOT NULL,
  `Dept_Name` VARCHAR(45) NOT NULL,
  `Office_Number` INT NOT NULL,
  `University` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Dept_Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Student` ;

CREATE TABLE IF NOT EXISTS `Student` (
  `Student_Number` INT NOT NULL,
  `SSN` INT NOT NULL,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Birth_Date` DATETIME NOT NULL,
  `Sex` VARCHAR(45) NOT NULL,
  `Class` VARCHAR(45) NOT NULL,
  `Degree_Program` VARCHAR(45) NOT NULL,
  `Current_Address` VARCHAR(45) NOT NULL,
  `Permanent_Address` VARCHAR(45) NOT NULL,
  `Contact_Number` INT NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  `ZIP` INT NOT NULL,
  `DEPARTMENT_Dept_Code` INT NOT NULL,
  `Minor_Dept_Code` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Student_Number`),
  CONSTRAINT `fk_Student_DEPARTMENT1`
    FOREIGN KEY (`DEPARTMENT_Dept_Code`)
    REFERENCES `DEPARTMENT` (`Dept_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Student_Number_UNIQUE` ON `Student` (`Student_Number` ASC) VISIBLE;

CREATE UNIQUE INDEX `SSN_UNIQUE` ON `Student` (`SSN` ASC) VISIBLE;

CREATE UNIQUE INDEX `Contact_Number_UNIQUE` ON `Student` (`Contact_Number` ASC) VISIBLE;

CREATE INDEX `fk_Student_DEPARTMENT1_idx` ON `Student` (`DEPARTMENT_Dept_Code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `COURSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `COURSE` ;

CREATE TABLE IF NOT EXISTS `COURSE` (
  `Course_Number` INT NOT NULL,
  `Course_Name` VARCHAR(45) NOT NULL,
  `Description` CHAR(200) NULL,
  `Credit_Hours` INT NOT NULL,
  `DEPARTMENT_Dept_Code` INT NOT NULL,
  PRIMARY KEY (`Course_Number`),
  CONSTRAINT `fk_COURSE_DEPARTMENT1`
    FOREIGN KEY (`DEPARTMENT_Dept_Code`)
    REFERENCES `DEPARTMENT` (`Dept_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_COURSE_DEPARTMENT1_idx` ON `COURSE` (`DEPARTMENT_Dept_Code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `SECTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SECTION` ;

CREATE TABLE IF NOT EXISTS `SECTION` (
  `Course_Number` INT NOT NULL,
  `Section_Number` INT NOT NULL,
  `Semester` INT NOT NULL,
  `Year` INT NOT NULL,
  `Instructor` VARCHAR(45) NOT NULL,
  `COURSE_Course_Number` INT NOT NULL,
  PRIMARY KEY (`Course_Number`, `Section_Number`, `Semester`, `Year`, `COURSE_Course_Number`),
  CONSTRAINT `fk_SECTION_COURSE`
    FOREIGN KEY (`COURSE_Course_Number`)
    REFERENCES `COURSE` (`Course_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_SECTION_COURSE_idx` ON `SECTION` (`COURSE_Course_Number` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `GRADE_REPORT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GRADE_REPORT` ;

CREATE TABLE IF NOT EXISTS `GRADE_REPORT` (
  `Student_Number` INT NOT NULL,
  `Course_Number` INT NOT NULL,
  `Section_Number` INT NOT NULL,
  `Semester` INT NOT NULL,
  `Year` INT NOT NULL,
  `GRADE` CHAR(3) NOT NULL,
  `CGPA` FLOAT NOT NULL,
  `SECTION_Course_Number` INT NOT NULL,
  `SECTION_Section_Number` INT NOT NULL,
  `SECTION_Semester` INT NOT NULL,
  `SECTION_Year` INT NOT NULL,
  `SECTION_COURSE_Course_Number` INT NOT NULL,
  `Student_Student_Number` INT NOT NULL,
  PRIMARY KEY (`Student_Number`, `Course_Number`, `Section_Number`, `Semester`, `Year`, `SECTION_Course_Number`, `SECTION_Section_Number`, `SECTION_Semester`, `SECTION_Year`, `SECTION_COURSE_Course_Number`, `Student_Student_Number`),
  CONSTRAINT `fk_GRADE_REPORT_SECTION1`
    FOREIGN KEY (`SECTION_Course_Number` , `SECTION_Section_Number` , `SECTION_Semester` , `SECTION_Year` , `SECTION_COURSE_Course_Number`)
    REFERENCES `SECTION` (`Course_Number` , `Section_Number` , `Semester` , `Year` , `COURSE_Course_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GRADE_REPORT_Student1`
    FOREIGN KEY (`Student_Student_Number`)
    REFERENCES `Student` (`Student_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Student_Number_UNIQUE` ON `GRADE_REPORT` (`Student_Number` ASC) VISIBLE;

CREATE INDEX `fk_GRADE_REPORT_SECTION1_idx` ON `GRADE_REPORT` (`SECTION_Course_Number` ASC, `SECTION_Section_Number` ASC, `SECTION_Semester` ASC, `SECTION_Year` ASC, `SECTION_COURSE_Course_Number` ASC) VISIBLE;

CREATE INDEX `fk_GRADE_REPORT_Student1_idx` ON `GRADE_REPORT` (`Student_Student_Number` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Department` ;

CREATE TABLE IF NOT EXISTS `Department` (
  `DeptCode` VARCHAR(10) NOT NULL,
  `DeptName` VARCHAR(100) NOT NULL,
  `OfficeNumber` VARCHAR(20) NULL DEFAULT NULL,
  `OfficePhone` VARCHAR(20) NULL DEFAULT NULL,
  `College` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`DeptCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `DeptName` ON `Department` (`DeptName` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Course` ;

CREATE TABLE IF NOT EXISTS `Course` (
  `CourseNumber` VARCHAR(10) NOT NULL,
  `CourseName` VARCHAR(100) NOT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `SemesterHours` INT NULL DEFAULT NULL,
  `Level` ENUM('Undergraduate', 'Graduate') NULL DEFAULT NULL,
  `DeptCode` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`CourseNumber`),
  CONSTRAINT `course_ibfk_1`
    FOREIGN KEY (`DeptCode`)
    REFERENCES `Department` (`DeptCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `DeptCode` ON `Course` (`DeptCode` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Student` ;

CREATE TABLE IF NOT EXISTS `Student` (
  `StudentNumber` INT NOT NULL,
  `SSN` CHAR(9) NOT NULL,
  `FirstName` VARCHAR(50) NULL DEFAULT NULL,
  `LastName` VARCHAR(50) NULL DEFAULT NULL,
  `CurrentStreet` VARCHAR(100) NULL DEFAULT NULL,
  `CurrentCity` VARCHAR(50) NULL DEFAULT NULL,
  `CurrentState` VARCHAR(50) NULL DEFAULT NULL,
  `CurrentZipCode` VARCHAR(10) NULL DEFAULT NULL,
  `CurrentPhone` VARCHAR(20) NULL DEFAULT NULL,
  `PermanentStreet` VARCHAR(100) NULL DEFAULT NULL,
  `PermanentCity` VARCHAR(50) NULL DEFAULT NULL,
  `PermanentState` VARCHAR(50) NULL DEFAULT NULL,
  `PermanentZipCode` VARCHAR(10) NULL DEFAULT NULL,
  `PermanentPhone` VARCHAR(20) NULL DEFAULT NULL,
  `BirthDate` DATE NULL DEFAULT NULL,
  `Sex` CHAR(1) NULL DEFAULT NULL,
  `Class` ENUM('Freshman', 'Sophomore', 'Junior', 'Senior', 'Graduate') NULL DEFAULT NULL,
  `DegreeProgram` ENUM('BTECH', 'MTECH') NOT NULL,
  `MajorDeptCode` VARCHAR(10) NOT NULL,
  `MinorDeptCode` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`StudentNumber`),
  CONSTRAINT `student_ibfk_1`
    FOREIGN KEY (`MajorDeptCode`)
    REFERENCES `Department` (`DeptCode`),
  CONSTRAINT `student_ibfk_2`
    FOREIGN KEY (`MinorDeptCode`)
    REFERENCES `Department` (`DeptCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `SSN` ON `Student` (`SSN` ASC) VISIBLE;

CREATE INDEX `MajorDeptCode` ON `Student` (`MajorDeptCode` ASC) VISIBLE;

CREATE INDEX `MinorDeptCode` ON `Student` (`MinorDeptCode` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Instructor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Instructor` ;

CREATE TABLE IF NOT EXISTS `Instructor` (
  `InstructorID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(50) NULL DEFAULT NULL,
  `LastName` VARCHAR(50) NULL DEFAULT NULL,
  `DeptCode` VARCHAR(10) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `Phone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`InstructorID`),
  CONSTRAINT `instructor_ibfk_1`
    FOREIGN KEY (`DeptCode`)
    REFERENCES `Department` (`DeptCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `DeptCode` ON `Instructor` (`DeptCode` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Section`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Section` ;

CREATE TABLE IF NOT EXISTS `Section` (
  `SectionID` INT NOT NULL AUTO_INCREMENT,
  `CourseNumber` VARCHAR(10) NOT NULL,
  `Semester` ENUM('Summer', 'Winter') NOT NULL,
  `Year` YEAR NOT NULL,
  `SectionNumber` INT NOT NULL,
  `InstructorID` INT NOT NULL,
  PRIMARY KEY (`SectionID`),
  CONSTRAINT `section_ibfk_1`
    FOREIGN KEY (`CourseNumber`)
    REFERENCES `Course` (`CourseNumber`),
  CONSTRAINT `section_ibfk_2`
    FOREIGN KEY (`InstructorID`)
    REFERENCES `Instructor` (`InstructorID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `CourseNumber` ON `Section` (`CourseNumber` ASC, `Semester` ASC, `Year` ASC, `SectionNumber` ASC) VISIBLE;

CREATE INDEX `InstructorID` ON `Section` (`InstructorID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `GradeReport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GradeReport` ;

CREATE TABLE IF NOT EXISTS `GradeReport` (
  `StudentNumber` INT NOT NULL,
  `SectionID` INT NOT NULL,
  `LetterGrade` CHAR(2) NULL DEFAULT NULL,
  `NumericGrade` INT NULL DEFAULT NULL,
  PRIMARY KEY (`StudentNumber`, `SectionID`),
  CONSTRAINT `gradereport_ibfk_1`
    FOREIGN KEY (`StudentNumber`)
    REFERENCES `Student` (`StudentNumber`),
  CONSTRAINT `gradereport_ibfk_2`
    FOREIGN KEY (`SectionID`)
    REFERENCES `Section` (`SectionID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `SectionID` ON `GradeReport` (`SectionID` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
